import importlib
import sys

_cache = {}

__all__ = [
    'AtaNumbering',
    'BrexChecker',
    'BrexNotFound',
    'ConsumablesList',
    'ConsumablesValidator',
    'CsnChecker',
    'DictError',
    'FCChecker',
    'GraphicRefChecker',
    'IPLChecker',
    'NoBrexDefined',
    'NoExcelSet',
    'NoOriginalTableFound',
    'NoXmlSet',
    'Punctuation',
    'RefChecker',
    'RepairSteps',
    'TorqueValuesValidator',
    'UiLoader',
    'UnitTable',
    'UnrecognizedUnit',
    'VendorList',
    'Worker',
    'WorkerSignals',
    'XmlSchemaValidator',
    '__check_line_widths',
    '_filter_widgets',
    '_ipl_to_dict_excel',
    'add_filename_version',
    'add_iplnom_to_smg',
    'add_iplnom_to_stp',
    'add_leading',
    'adjust_column_widths',
    'baselineReportFilter',
    'batch',
    'batch_check_line_widths',
    'batch_check_text_format',
    'blueprint',
    'calculate_image_similarity',
    'calculate_points',
    'cgm2svg',
    'cgm2svgclear',
    'check_brackets',
    'check_cgm_details',
    'check_icn',
    'check_icns',
    'check_illu_text',
    'check_line_widths',
    'check_text_format',
    'check_tif_details',
    'clean_path',
    'clean_word',
    'clean_xml_tags',
    'clean_xpath',
    'clearCGM2SVG',
    'colum_number_to_letter',
    'compress_img',
    'cons_and_teds_checker',
    'convert_image_to_pdf',
    'copy_files',
    'copy_pdf_column',
    'count_lines_of_functions',
    'crop_image',
    'delete_filename_version',
    'delete_first_line',
    'docx_content_replace',
    'docx_footer_replace',
    'docx_header_replace',
    'download_excel',
    'estimate_illustration',
    'extract_rows_from_page',
    'fill',
    'find_characters',
    'find_document_by_reference',
    'format_excel',
    'fourDigits',
    'getContent',
    'get_2and3_refs',
    'get_4plus_refs',
    'get_average_color',
    'get_brex_ref',
    'get_chrome_driver_version',
    'get_ddn',
    'get_dm_code_from_filename',
    'get_dm_code_from_xml',
    'get_dm_codes_from_dir',
    'get_excel_sheet_names',
    'get_extensions',
    'get_file_size',
    'get_font_types',
    'get_footer_type',
    'get_manual_series',
    'get_object_attributes',
    'get_object_methods',
    'get_ocr_pdf_content',
    'get_pdf_content',
    'get_pdf_metadata',
    'get_references',
    'get_regex_string',
    'get_s1000d_refs',
    'get_s1000d_version',
    'get_schema_from_xml',
    'get_svg_data',
    'get_table_column_widths',
    'get_template_version',
    'get_textfile_content',
    'get_xml_attribute',
    'get_xml_tag_content',
    'glb2dracoglb',
    'illu_date_check',
    'illustrationChecker',
    'include_search_bar',
    'increase_filename_version',
    'increase_issue_number',
    'ipl_to_dict',
    'is_fullpage_illu',
    'linePrepend',
    'linearize_xml',
    'list_files',
    'list_files2',
    'list_files3',
    'load_ui',
    'make_library',
    'merge_pdfs',
    'negative',
    'ocr_pdf',
    'oneDigit',
    'pdf2raster',
    'pdf_date_to_format',
    'pdf_page_count',
    'pdf_page_to_img',
    'pdf_to_dictionary',
    'pgblk_9000_ted_checker',
    'prepare_estimation',
    'preprocess_svg',
    'prettyPrint',
    'raster2pdf',
    'rbg2hex',
    'read_description',
    'read_dmodule',
    'read_procedure',
    'read_word_footers',
    'ref_dict_to_dm_code_dict',
    'ref_dict_to_str',
    'ref_dict_to_xml',
    'rename_illustrations',
    'replace_copyright',
    'replace_media',
    'replace_special_characters',
    'resize_img',
    'set_inwork',
    'set_xml_attribute',
    'set_xml_tag_content',
    'seven_unzip',
    'simple_pretty_print',
    'ste_dict_rows',
    'string_similarity',
    'stroke',
    'strokeWidth',
    'svg2jpg',
    'svg2pdf',
    'svgCircle',
    'svgPolyline',
    'svgText',
    'threeDigits',
    'to_256',
    'twoDigits',
    'unarchive_file',
    'update_chrome_driver',
    'update_filename_version',
    'update_footer_table_widths',
    'validate_ddn',
    'validate_references',
    'validate_word',
    'word2pdf',
    'word_frequency',
    'zip_excel_folder',
    'zip_folder',
    'zip_word_folder',
    'zipdir',
]

def __getattr__(name):
    if name in _cache:
        return _cache[name]
    modules = {
        'AtaNumbering': 'ataispec2200',
        'BrexChecker': 'brex_checker',
        'BrexNotFound': 'brex_checker',
        'ConsumablesList': 'consTableValidator',
        'ConsumablesValidator': 'ataispec2200',
        'CsnChecker': 'reference_checker',
        'DictError': 'consTableValidator',
        'FCChecker': 'fits_and_clearences_checker',
        'GraphicRefChecker': 'reference_checker',
        'IPLChecker': 'procedure_checker',
        'NoBrexDefined': 'brex_checker',
        'NoExcelSet': 'consTableValidator',
        'NoOriginalTableFound': 'consTableValidator',
        'NoXmlSet': 'ataispec2200',
        'Punctuation': 'xml_validation',
        'RefChecker': 'reference_checker',
        'RepairSteps': 'repair_steps',
        'TorqueValuesValidator': 'ataispec2200',
        'UiLoader': 'utils',
        'UnitTable': 'unit_table',
        'UnrecognizedUnit': 'unit_table',
        'VendorList': 'vendor_list',
        'Worker': 'multi',
        'WorkerSignals': 'multi',
        'XmlSchemaValidator': 'xml_validation',
        '__check_line_widths': 'svg_checks',
        '_filter_widgets': 'search_bar',
        '_ipl_to_dict_excel': 'ataispec2200',
        'add_filename_version': 'filename_version',
        'add_iplnom_to_smg': 'smg',
        'add_iplnom_to_stp': 'stp',
        'add_leading': 'txt',
        'adjust_column_widths': 'docx_',
        'baselineReportFilter': 'illustrations_checker',
        'batch': 'batcher',
        'batch_check_line_widths': 'svg_checks',
        'batch_check_text_format': 'svg_checks',
        'blueprint': 'graphics',
        'calculate_image_similarity': 'compare_raster',
        'calculate_points': 'clearcgm2svg',
        'cgm2svg': 'cgm2svg',
        'cgm2svgclear': 'cgm2clearcgm',
        'check_brackets': 'python_func',
        'check_cgm_details': 'illustration_checks',
        'check_icn': 'svg_checks',
        'check_icns': 'svg_checks',
        'check_illu_text': 'svg_checks',
        'check_line_widths': 'svg_checks',
        'check_text_format': 'svg_checks',
        'check_tif_details': 'illustration_checks',
        'clean_path': 'filepath',
        'clean_word': 'data_extraction',
        'clean_xml_tags': 'repair_steps',
        'clean_xpath': 'brex_checker',
        'clearCGM2SVG': 'clearcgm2svg',
        'colum_number_to_letter': 'excel_',
        'compress_img': 'graphics',
        'cons_and_teds_checker': 'ataispec2200',
        'convert_image_to_pdf': 'raster2pdf',
        'copy_files': 'copying',
        'copy_pdf_column': 'extract_rows',
        'count_lines_of_functions': 'python_func',
        'crop_image': 'graphics',
        'delete_filename_version': 'filename_version',
        'delete_first_line': 'xml_processing',
        'docx_content_replace': 'docx_',
        'docx_footer_replace': 'docx_',
        'docx_header_replace': 'docx_',
        'download_excel': 'excel_',
        'estimate_illustration': 'estimation',
        'extract_rows_from_page': 'extract_rows',
        'fill': 'clearcgm2svg',
        'find_characters': 'txt',
        'find_document_by_reference': 's1000d',
        'format_excel': 'excel_',
        'fourDigits': 'clearcgm2svg',
        'getContent': 'clearcgm2svg',
        'get_2and3_refs': 's1000d',
        'get_4plus_refs': 's1000d',
        'get_average_color': 'graphics',
        'get_brex_ref': 's1000d',
        'get_chrome_driver_version': 'vendor_list',
        'get_ddn': 's1000d',
        'get_dm_code_from_filename': 's1000d',
        'get_dm_code_from_xml': 's1000d',
        'get_dm_codes_from_dir': 's1000d',
        'get_excel_sheet_names': 'excel_',
        'get_extensions': 'filelist',
        'get_file_size': 'file_info',
        'get_font_types': 'clearcgm2svg',
        'get_footer_type': 'docx_',
        'get_manual_series': 'make_library',
        'get_object_attributes': 'python_func',
        'get_object_methods': 'python_func',
        'get_ocr_pdf_content': 'ocr_pdf',
        'get_pdf_content': 'pdf',
        'get_pdf_metadata': 'pdf',
        'get_references': 's1000d',
        'get_regex_string': 'docx_',
        'get_s1000d_refs': 's1000d',
        'get_s1000d_version': 's1000d',
        'get_schema_from_xml': 'xml_processing',
        'get_svg_data': 'svg_data',
        'get_table_column_widths': 'docx_',
        'get_template_version': 'docx_',
        'get_textfile_content': 'txt',
        'get_xml_attribute': 'xml_processing',
        'get_xml_tag_content': 'xml_processing',
        'glb2dracoglb': 'glb2dracoglb',
        'illu_date_check': 'illustration_checks',
        'illustrationChecker': 'illustrations_checker',
        'include_search_bar': 'search_bar',
        'increase_filename_version': 'filename_version',
        'increase_issue_number': 's1000d',
        'ipl_to_dict': 'ataispec2200',
        'is_fullpage_illu': 'estimation',
        'linePrepend': 'clearcgm2svg',
        'linearize_xml': 'xml_processing',
        'list_files': 'filelist',
        'list_files2': 'filelist',
        'list_files3': 'filelist',
        'load_ui': 'utils',
        'make_library': 'make_library',
        'merge_pdfs': 'pdf',
        'negative': 'graphics',
        'ocr_pdf': 'ocr_pdf',
        'oneDigit': 'clearcgm2svg',
        'pdf2raster': 'pdf2raster',
        'pdf_date_to_format': 'time',
        'pdf_page_count': 'pdf',
        'pdf_page_to_img': 'extract_rows',
        'pdf_to_dictionary': 'extract_rows',
        'pgblk_9000_ted_checker': 'ataispec2200',
        'prepare_estimation': 'estimation',
        'preprocess_svg': 'clearcgm2svg',
        'prettyPrint': 'clearcgm2svg',
        'raster2pdf': 'raster2pdf',
        'rbg2hex': 'clearcgm2svg',
        'read_description': 's1000d',
        'read_dmodule': 's1000d',
        'read_procedure': 's1000d',
        'read_word_footers': 'docx_',
        'ref_dict_to_dm_code_dict': 's1000d',
        'ref_dict_to_str': 's1000d',
        'ref_dict_to_xml': 's1000d',
        'rename_illustrations': 'batcher',
        'replace_copyright': 'docx_',
        'replace_media': 'docx_',
        'replace_special_characters': 'xml_processing',
        'resize_img': 'graphics',
        'set_inwork': 's1000d',
        'set_xml_attribute': 'xml_processing',
        'set_xml_tag_content': 'xml_processing',
        'seven_unzip': 'archive',
        'simple_pretty_print': 'python_func',
        'ste_dict_rows': 'extract_rows',
        'string_similarity': 'txt',
        'stroke': 'clearcgm2svg',
        'strokeWidth': 'clearcgm2svg',
        'svg2jpg': 'svg2jpg',
        'svg2pdf': 'svg2pdf',
        'svgCircle': 'clearcgm2svg',
        'svgPolyline': 'clearcgm2svg',
        'svgText': 'clearcgm2svg',
        'threeDigits': 'clearcgm2svg',
        'to_256': 'graphics',
        'twoDigits': 'clearcgm2svg',
        'unarchive_file': 'archive',
        'update_chrome_driver': 'vendor_list',
        'update_filename_version': 'filename_version',
        'update_footer_table_widths': 'docx_',
        'validate_ddn': 's1000d',
        'validate_references': 's1000d',
        'validate_word': 'txt',
        'word2pdf': 'docx_',
        'word_frequency': 'txt',
        'zip_excel_folder': 'archive',
        'zip_folder': 'archive',
        'zip_word_folder': 'archive',
        'zipdir': 'archive',
    }
    if name in modules:
        module = importlib.import_module(f'.{modules[name]}', __package__)
        value = getattr(module, name)
        _cache[name] = value
        return value
    raise AttributeError(f'module {__name__} has no attribute {name}')
